### ISSUE TITLE
No service when player isn't running

### ISSUE THREAD

**Issue by z9xx7o0** [Angel-Studio/SoundTap#12]
**Is your feature request related to a problem? Please describe.**

When I finish listening to music and close my music player app, every time I want to adjust the sound, the app does its thing. 

**Describe the solution you'd like**

The app detects if a player is active, and if it's true, then it will do its thing. I don't mean close and open, I mean: if a player isn't running, I can long press my volume as much as I want, and the app won't interfere. But if a player is running, then it will.

**Describe alternatives you've considered**

**Additional context**

**Comment by JulesPvx** [comment]
Okay, I see what's going on here, thanks for the feedback! I'll try to fix that quickly (it was already a feature haha)

**Comment by JulesPvx** [comment]
Should be fixed in 1.1.4 :)
