### ISSUE TITLE
Can't select preferred player

### ISSUE THREAD

**Issue by z9xx7o0** [Angel-Studio/SoundTap#13]
**Describe the bug**
When I want to select my preferred player, all I get is spotify

**To Reproduce**
No steps are needed.

**Expected behavior**
I get the option to select [Namida](https://github.com/namidaco/namida) as my preferred music player

**Screenshots**
![Screenshot_20240701_191254_SoundTap.png](https://github.com/Angel-Studio/SoundTap/assets/83415416/2e23147c-9cbb-4c93-b9cb-ce7af5eb2052)

**Smartphone**
 - Device: [Samsung galaxys 23 ultra]
 - Version [OneUI 6.1]

**Additional context**
I have two players, Spotify and Namida. I prefer Namida, but it doesn't allow me to select it.

**Comment by JulesPvx** [comment]
Yeah this is the only media player that supports auto play, that's why. I'll test with your media player too, and add it if it works :) (I will also add a text describing what it does in the app)

**Comment by z9xx7o0** [comment]
Ahh, what I meant with the preferred player is:
If I have two players open at once, the preferred player is the one that will be controlled(because you can't control both, so you pick the preferred one)

**Comment by z9xx7o0** [comment]
Also, I just found a problem related to this:
Here, I have two players, one is currently playing a track, while the other is not. When I use the app, it only does it(English is my second language) with spotify while ignoring the active one. 
https://github.com/Angel-Studio/SoundTap/assets/83415416/9aedcbd0-be55-43bf-9760-a7621b4095f5

**Comment by JulesPvx** [comment]
> Also, I just found a problem related to this: Here, I have two players, one is currently playing a track, while the other is not. When I use the app, it only does it(English is my second language) with spotify while ignoring the active one. https://github.com/Angel-Studio/SoundTap/assets/83415416/9aedcbd0-be55-43bf-9760-a7621b4095f5

Yeah it actually picks the first media player registered, I'll make it so that it will use the preferred one if it is running, else it will use whatever is playing.
I'll also make it prioritize the one playing since this was what it was about x)
Thanks for the feedback tho, really appreciate it :) If you have any otehr issues feel free to let me know

**Comment by JulesPvx** [comment]
Will be fixed in 1.1.4 ;)
