### ISSUE TITLE
[Issue] app doesn't work when the screen is off.

### ISSUE THREAD

**Issue by z9xx7o0** [Angel-Studio/SoundTap#14]

**Comment by z9xx7o0** [comment]
Even when selecting screen on & off or just screen off, the app doesn't work.

**Comment by JulesPvx** [comment]
Yeah probably because starting with Android 12 there's a bug. You actually need to keep Always on display ON for it to work :(

**Comment by JulesPvx** [comment]
Added a message explaining this in the new versions

**Comment by TempUser13** [comment]
Do you have any more info about the a12+ bug or the issue tracker link or anything?

**Comment by JulesPvx** [comment]
> Do you have any more info about the a12+ bug or the issue tracker link or anything?

It's still not fixed in the latest Android 15 beta versions :/ hope they fix this some day

**Comment by JulesPvx** [comment]
There might be a way using root access tho, I need to take time to check this out

**Comment by TempUser13** [comment]
Do you know what the actual bug is or just that it exists? I'm asking because if there's specifics I was going to ask the developers of the Custom OS I use and see if they would patch it themselves.

**Comment by JulesPvx** [comment]
It's probably some optimization thing that makes it so that the key events are not sent to apps that have registered broadcast services. It's from the accessibility service key receiver.

**Comment by TempUser13** [comment]
I found the Google [Issue](https://issuetracker.google.com/issues/201546605) and apparently there's a [workaround](https://issuetracker.google.com/issues/201546605#comment193) and [this](https://issuetracker.google.com/issues/201546605#comment167) is why the issue was never fixed.

**Comment by JulesPvx** [comment]
Oh okay, thanks for your search! Sadly, the workaround won't work for us since the app needs to cancel the volume events to prevent the phone from changing the volume :/

And even if we wanted to work with it, we'd have to change the way the app works, since we don't receive the same data at all. And if I read correctly, it wouldn't even work on all phones :c

**Comment by TempUser13** [comment]
Ah okay, it was worth a look.
