### ISSUE TITLE
Cant Continue/Open The App

### ISSUE THREAD

**Issue by Skullhunter11** [Angel-Studio/SoundTap#3]
**Describe the bug**
Cannot open continue/open the app for some reason it just stay on the this and I'm just stuck here.

**Screenshots**
![Screenshot_20240526_191151_SoundTap.jpg](https://github.com/Angel-Studio/SoundTap/assets/104146790/ffcf11f5-6d4c-40d2-a158-d3f55447ac85)

**App Version**
- 1.0.4

**Smartphone**
 - Device: Samsung A15
 - Android Version: 14

**Comment by JulesPvx** [comment]
Let me know if the last 1.0.5-alpha update fixes it, I'm not sure on how to fix this and can't seem to reproduce it haha. Hope the changes I made fixes it !
