### ISSUE TITLE
Crashing when clicking for customisation

### ISSUE THREAD

**Issue by foenicxxx** [Angel-Studio/SoundTap#5]
**Describe the bug**
Just after installing the app from playstore and giving all the needed permission, when I try to customise and click the customise button, the app just crashes.

**Smartphone (please complete the following information):**
 - Device: LG G8X
 - Version Android 12
[
![Screenshot_20240526-213951](https://github.com/Angel-Studio/SoundTap/assets/95611057/2756a3b3-54f8-4550-9d2c-9f253113e3d0)
](url)

**Comment by JulesPvx** [comment]
Thanks for the feedback, this seems to be a compose issue. I've removed an experimental feature that could produce this bug. Let me know if the last 1.0.5-alpha version fixes it, else I'll report it to google ;)
