### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NripPrajapat** [Angel-Studio/SoundTap#8]
**Describe the bug**
It crashes when I click on customize. 
**To Reproduce**
Go to customize and it will crash. 

**Expected behavior**
Crash. 

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - Version 14.0.600

**Comment by JulesPvx** [comment]
Fixed on v1.0.7 hotfix ;)

**Comment by NripPrajapat** [comment]
It is worse now, crash at the startup.

**Comment by NripPrajapat** [comment]
It stops working as soon as I turn on (allow) accessibility services.
It shows player initially.
But then app crashes because of accessibility.
In end, after 10 tries, It works fine except 
It won't work with 'Musicloet'. It won't display the current playing song.
It gives an option to 'open' spotify.
Although it works fine in the background. (it changes tracks as it should.)

**Comment by JulesPvx** [comment]
Oh yeah thanks, got it, found the bug. I'll fix it in the afternoon, thanks :)

**Comment by JulesPvx** [comment]
**- Fixed in v1.0.9**
